title: Dinesh Kumar Reddy Guvva
description: Have a very strong technical background in UNIX, Shell Scripting, Python scripting, SQL with 8 years of experience. 
             hands-on experience in ML, NLP and Pandas, NumPy libraries and development of dashboards and chatbots.

theme: jekyll-theme-cayman
